name: CI workflow

""" Triggers events """
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

""" Uses ubuntu-latest runner for the job """
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim